#!/usr/bin/env bash

\rm -f target src/main/java/bytecode/*.class

clear

run() {
  echo -e "\\033[1m\$ $*\\033[0m"
  $*
}

commentaire() {
  echo ""
  echo -e "\\033[32m# $*\\033[0m"
}

enter() {
  echo -en "\\033[31m[...]\\033[0m"
  read
}

show() {
  #echo -en "\\033[92m"
  $* | pygmentize -l xml
  #echo -en "\\033[0m"
  enter
}

commentaire "javac compilation with JDK 7..."
j7
run javac -version src/main/java/bytecode/Display.java 


commentaire "then run with JRE 7..."
run java -cp src/main/java bytecode.Display

enter

commentaire "running with JRE 8: runs smoothly since binary compatibility..."
j8
run java -cp src/main/java bytecode.Display

enter

commentaire "but if run with JRE 6: binary incompatibility..."
j6
run java -cp src/main/java bytecode.Display

enter

clear
commentaire "Maven compilation with JDK 7..."
show grep -B 7 -A 1 project.build.sourceEncoding pom.xml
j7
run mvn clean compile


commentaire "then run with JRE 7..."
run java -cp target/classes bytecode.Display
commentaire "generated bytecode is version 5, because forced by maven-compiler-plugin by default"

enter

clear
commentaire "Maven compilation with JDK 7 but maven.compiler.source & target properties set to 1.6..."
show grep -B 2 -A 2 maven.compiler.source pom-properties.xml
run mvn clean compile -f pom-properties.xml
run java -cp target/classes bytecode.Display

commentaire "this time, execution with JRE 6 doesn't cause any failure..."
j6
run java -cp target/classes bytecode.Display

enter

clear
commentaire "unless a dependency brings in version 7 bytecode..."
run java -cp target/classes:lib/* bytecode.Display2

enter

clear
commentaire "enforceBytecodeVersion rule from maven-enforcer-plugin checks dependencies bytecode version..."
show grep -B 2 -A 25 maven-enforcer-plugin pom-enforcer.xml
run mvn clean compile -f pom-enforcer.xml
commentaire "then detects the issue at compile time..."
